### ISSUE TITLE
missing arguments

### ISSUE THREAD

**Issue by AYUSH27112021** [vasistalodagala/whisper-finetune#1]
in line 10 of data_prep.py the .txt arguments are missing which are causing directory errors please update it
scp_entries = open(f"{args.source_data_dir}/audio_paths**.txt**", 'r').readlines()
txt_entries = open(f"{args.source_data_dir}/text**.txt**", 'r').readlines()

**Comment by vasistalodagala** [comment]
Hi @AYUSH27112021 ,
A few lines of comments have been added to the [data preparation section](https://github.com/vasistalodagala/whisper-finetune#data-preparation-for-custom-datasets) of the repository for better understanding of the process. 

There is no need to have any extensions for the `audio_paths` and `text` files. They are to be named as is. In case you prefer to have extensions for your use case, you may modify the `data_prep.py` accordingly. However, in general there is no extension requirements on these files.

Also, please note that the `source_data_directory` should be containing the `audio_paths` and `text` files. 

In case you are dealing with multiple custom datasets, you may run the data preparation stage independently for each of the datasets and use them in the [fine-tuning](https://github.com/vasistalodagala/whisper-finetune#fine-tune-on-a-custom-dataset) and [evaluation](https://github.com/vasistalodagala/whisper-finetune#evaluate-on-a-custom-dataset) stages which support multiple dataset parsing. This makes it easier to maintain and manage the datasets at hand.
