### ISSUE TITLE
Fine tuning whisper model on custom dataset -- trainer error.

### ISSUE THREAD

**Issue by Subhanshu20101** [vasistalodagala/whisper-finetune#5]
I am running the fine-tuning script on a custom dataset. In the ```trainer``` initialization,
```
trainer = Seq2SeqTrainer(
    training_args,
    model=model,
    train_dataset=raw_dataset["train"],
    eval_dataset=raw_dataset["eval"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.feature_extractor,
)
```
I am getting a ```TypeError: __init__() got multiple values for argument 'model'``` .
Can anyone help me with this?

**Comment by vasistalodagala** [comment]
Could you please share here the parameter you're passing for the argument named `--model_name` ?
It should be a string carrying the model name on huggingface without any spaces. For example: `openai/whisper-small` would be a valid argument while `openai/ whisper-small` wouldn't be.

**Comment by Subhanshu20101** [comment]
I am passing ```model_name = 'openai/whisper-base'```.

**Comment by Subhanshu20101** [comment]
And model is initialised as ```model = WhisperForConditionalGeneration.from_pretrained(model_name)```.

**Comment by vasistalodagala** [comment]
Okay. So this seems to be an issue with the way you're passing the arguments to the [Seq2SeqTrainer](https://github.com/huggingface/transformers/blob/v4.28.1/src/transformers/trainer_seq2seq.py#L42)'s `__init__()`. 
What the class expects is the model first followed by the training arguments etc., as mentioned in its definition from the above link.
So, you could do one of the following two things while defining `trainer`:
1. passing the model first and then the training arguments as mentioned in the class definition.
```bash
trainer = Seq2SeqTrainer(
    model=model,
    training_args,
    train_dataset=raw_dataset["train"],
    eval_dataset=raw_dataset["eval"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.feature_extractor,
)
```

2. Explicitly mention `args` as suggested in the [code](https://github.com/vasistalodagala/whisper-finetune/blob/master/train/fine-tune_on_custom_dataset.py#L330).
```bash
trainer = Seq2SeqTrainer(
    args=training_args,
    model=model,
    train_dataset=raw_dataset["train"],
    eval_dataset=raw_dataset["eval"],
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    tokenizer=processor.feature_extractor,
)
```

**Comment by Subhanshu20101** [comment]
Thanks I understood the issue.
